### ISSUE TITLE
Error trying to run AllHackingTools

### ISSUE THREAD

**Issue by xlxmattchubxlx** [mishakorzik/AllHackingTools#37]
Well, when I first installed AHT, everything goes smoothly but then I try to run it, It ACTS like it wants t load but then it ends with this error

`Traceback (most recent call last):
  File "ipsend.py", line 13, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.10/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/data/data/com.termux/files/usr/lib/python3.10/smtplib.py", line 642, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/data/data/com.termux/files/usr/lib/python3.10/smtplib.py", line 432, in docmd
    return self.getreply()
  File "/data/data/com.termux/files/usr/lib/python3.10/smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
Options:`

Even tried to do a **clean install** with a fresh Termux

**Comment by mishakorzik** [comment]
You operating system

**Comment by mishakorzik** [comment]
Reinstall
