### ISSUE TITLE
line 31

### ISSUE THREAD

**Issue by hello12332145** [mishakorzik/AllHackingTools#63]
Traceback (most recent call last):
  File "C:/Users/chees/Downloads/python stuff/hacking thing.py", line 31, in <module>
    op=int("raw_input"("Options: "))
TypeError: 'str' object is not callable

**Comment by koussay1** [comment]
hey bro , i got this error :
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/AllHackingTools/MainMenu.py", line 31, in <module>
    op=int(raw_input("Options: "))
           ^^^^^^^^^
NameError: name 'raw_input' is not defined

**Comment by koussay1** [comment]
Hi bro , i got this error too but i solved it in few steps :
First , go to  AllHackingTools folder and type folder .
Second , type nano MainMenu.py ( this will show you the MainMenu code)
Third , replace the line 31 with this :
op=int(raw_input("Options: "))
Now , quit and save by clicking in CTRl+x then press y , after all that , press enter
Finally don't use python3 use python2 by typing : python2 MainMenu.py 
I hope this helps you , if you got any problem contact me .

**Comment by mishakorzik** [comment]
I'm sorry but I can't help you because "python stuff" its not my tool.
